In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ASUS\anaconda3\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ASUS\anaconda3\Lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ASUS\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ASUS\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ASUS\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
# 1. Load the dataset into a Pandas DataFrame.
df = pd.read_csv("airbnb_dirty_dataset.csv")
df

,listing_id,city,property_type,price,rating,reviews,minimum_nights,host,availability_days,last_booked
0,1000,Delhi,Apartment,5412.0,3.8,211.0,9,Host_23,302,2025-08-05
1,1001,Mumbai,Apartment,7670.0,4.3,214.0,9,NaN,332,2025-12-26
2,1002,Ahmedabad,Villa,3813.0,4.3,1100.0,7,Host_88,142,2025-03-21
3,1003,Goa,NaN,4204.0,3.9,NaN,6,NaN,135,2025-01-23
4,1004,Chennai,House,9020.0,5.0,93.0,15,Host_221,185,2025-10-23
...,...,...,...,...,...,...,...,...,...,...
995,1839,Jaipur,House,4785.0,4.1,230.0,7,Host_93,322,2025-12-07
996,1516,Bengaluru,Loft,800.0,NaN,NaN,13,Host_125,153,2025-05-09
997,1389,Chennai,Villa,NaN,3.6,134.0,6,Host_42,132,2025-12-19
998,1921,Mumbai,Studio,4318.0,3.2,315.0,7,Host_211,296,2025-12-02
999,1494,Delhi,Villa,NaN,4.2,39.0,1,Host_42,199,2025-11-22

In [4]:
# 2. Display the first 10 and last 10 rows.
print(df.head(10))
print(df.tail(10))

   listing_id       city property_type   price  rating  reviews  \
0        1000      Delhi     Apartment  5412.0     3.8    211.0
1        1001     Mumbai     Apartment  7670.0     4.3    214.0
2        1002  Ahmedabad         Villa  3813.0     4.3   1100.0
3        1003        Goa           NaN  4204.0     3.9      NaN
4        1004    Chennai         House  9020.0     5.0     93.0
5        1005        Goa     Apartment  8483.0     4.3    177.0
6        1006  Ahmedabad        Studio  1507.0     4.5     55.0
7        1007      Delhi         House  8085.0     3.8    108.0
8        1008        Goa        Studio  7596.0     3.5    179.0
9        1009       Pune         Villa  5883.0     3.3    214.0

   minimum_nights      host  availability_days last_booked
0               9   Host_23                302  2025-08-05
1               9       NaN                332  2025-12-26
2               7   Host_88                142  2025-03-21
3               6       NaN                135  2025-01-23
4              15  Host_221                185  2025-10-23
5               2  Host_219                119  2025-02-21
6              12  Host_240                349  2025-11-28
7               8   Host_98                138  2025-11-24
8               5   Host_17                108  2025-10-18
9               8   Host_37                135  2025-03-13
     listing_id       city property_type   price  rating  reviews  \
990        1213        Goa           NaN  8219.0     4.1     76.0
991        1778     Mumbai          Loft  2163.0     NaN     43.0
992        1481  Bengaluru         House  6373.0     NaN    109.0
993        1893    Chennai     Apartment  3101.0     4.0    105.0
994        1022  Ahmedabad          Loft  2020.0     4.4    151.0
995        1839     Jaipur         House  4785.0     4.1    230.0
996        1516  Bengaluru          Loft   800.0     NaN      NaN
997        1389    Chennai         Villa     NaN     3.6    134.0
998        1921     Mumbai        Studio  4318.0     3.2    315.0
999        1494      Delhi         Villa     NaN     4.2     39.0

     minimum_nights      host  availability_days last_booked
990               8   Host_81                214  2025-03-19
991               4  Host_247                142  2025-03-16
992               5  Host_237                 92  2025-09-22
993               1  Host_235                 17  2025-07-13
994               7       NaN                173  2025-02-25
995               7   Host_93                322  2025-12-07
996              13  Host_125                153  2025-05-09
997               6   Host_42                132  2025-12-19
998               7  Host_211                296  2025-12-02
999               1   Host_42                199  2025-11-22

In [5]:
# 3. Find the number of rows and columns.
print(df.sample)

<bound method NDFrame.sample of      listing_id       city property_type   price  rating  reviews  \
0          1000      Delhi     Apartment  5412.0     3.8    211.0
1          1001     Mumbai     Apartment  7670.0     4.3    214.0
2          1002  Ahmedabad         Villa  3813.0     4.3   1100.0
3          1003        Goa           NaN  4204.0     3.9      NaN
4          1004    Chennai         House  9020.0     5.0     93.0
..          ...        ...           ...     ...     ...      ...
995        1839     Jaipur         House  4785.0     4.1    230.0
996        1516  Bengaluru          Loft   800.0     NaN      NaN
997        1389    Chennai         Villa     NaN     3.6    134.0
998        1921     Mumbai        Studio  4318.0     3.2    315.0
999        1494      Delhi         Villa     NaN     4.2     39.0

     minimum_nights      host  availability_days last_booked
0                 9   Host_23                302  2025-08-05
1                 9       NaN                332  2025-12-26
2                 7   Host_88                142  2025-03-21
3                 6       NaN                135  2025-01-23
4                15  Host_221                185  2025-10-23
..              ...       ...                ...         ...
995               7   Host_93                322  2025-12-07
996              13  Host_125                153  2025-05-09
997               6   Host_42                132  2025-12-19
998               7  Host_211                296  2025-12-02
999               1   Host_42                199  2025-11-22

[1000 rows x 10 columns]>

In [6]:
# 4. Display the data types of all columns.
print(df.dtypes)

listing_id             int64
city                  object
property_type         object
price                float64
rating               float64
reviews              float64
minimum_nights         int64
host                  object
availability_days      int64
last_booked           object
dtype: object

In [7]:
# 5. Count the missing (NaN) values in each column.
df.isnull().sum()

listing_id            0
city                 49
property_type        52
price                49
rating               52
reviews              51
minimum_nights        0
host                 51
availability_days     0
last_booked           0
dtype: int64

In [9]:
# 6. Fill missing values in 'price' with the mean price.
df["price"] = df["price"].fillna(df["price"].mean())

In [10]:
# 7. Fill missing values in 'rating' with the median rating.
# df["rating"].median()
df["rating"] = df["rating"].fillna(df["rating"].median())

In [11]:
# 8. Fill missing values in 'city', 'property_type', and 'host' with the mode.
df["city"].mode()
df["city"]= df["city"].fillna(df["city"].mode()[0])
df["property_type"] .mode()
df["property_type"]= df["property_type"].fillna(df["property_type"].mode()[0])
df["host"] .mode()
df["host"] = df["host"].fillna(df["host"].mode()[0])

In [12]:
# 9. Count duplicate rows
print(df.duplicated().sum())

20

In [37]:
# 10. Remove all duplicate rows.
df = df.drop_duplicates()

In [38]:
# 11. Show all listings where price > 50000.
print(df[df["price"] > 5000])

     listing_id     city property_type   price  rating  reviews  \
0          1000    Delhi     Apartment  5412.0     3.8    211.0
1          1001   Mumbai     Apartment  7670.0     4.3    214.0
4          1004  Chennai         House  9020.0     5.0     93.0
5          1005      Goa     Apartment  8483.0     4.3    177.0
7          1007    Delhi         House  8085.0     3.8    108.0
..          ...      ...           ...     ...     ...      ...
972        1972   Jaipur          Loft  5577.0     3.1    190.0
973        1973      Goa          Loft  7318.0     4.5    121.0
975        1975    Delhi          Loft  6764.0     4.3    165.0
977        1977     Pune     Apartment  7083.0     3.5    134.0
978        1978   Mumbai          Loft  5656.0     4.1    137.0

     minimum_nights      host  availability_days last_booked
0                 9   Host_23                302  2025-08-05
1                 9  Host_166                332  2025-12-26
4                15  Host_221                185  2025-10-23
5                 2  Host_219                119  2025-02-21
7                 8   Host_98                138  2025-11-24
..              ...       ...                ...         ...
972              13   Host_89                 73  2025-05-18
973               8    Host_1                 49  2025-02-05
975              12   Host_47                 98  2025-05-13
977               2    Host_3                 31  2025-05-17
978               9  Host_247                136  2025-09-06

[586 rows x 10 columns]

In [39]:
# 12. Show listings where rating >= 4.5.
print(df[df["rating"] >= 4.5])

     listing_id       city property_type    price  rating  reviews  \
4          1004    Chennai         House   9020.0     5.0     93.0
6          1006  Ahmedabad        Studio   1507.0     4.5     55.0
11         1011     Mumbai          Loft   4454.0     4.6    209.0
12         1012    Chennai         House   5475.0     4.8    105.0
15         1015     Mumbai         House   3189.0     5.0      NaN
..          ...        ...           ...      ...     ...      ...
962        1962    Chennai          Loft   2832.0     4.5    216.0
963        1963      Delhi        Studio  10028.0     4.7    212.0
964        1964    Chennai        Studio   3374.0     4.7    171.0
966        1966       Pune          Loft   3185.0     5.0    284.0
973        1973        Goa          Loft   7318.0     4.5    121.0

     minimum_nights      host  availability_days last_booked
4                15  Host_221                185  2025-10-23
6                12  Host_240                349  2025-11-28
11               10   Host_17                197  2025-07-15
12               15  Host_138                136  2025-11-25
15               15  Host_213                157  2025-05-03
..              ...       ...                ...         ...
962               8    Host_6                195  2025-08-07
963               5   Host_98                237  2025-06-06
964               3  Host_235                 97  2025-01-03
966               2   Host_99                289  2025-03-25
973               8    Host_1                 49  2025-02-05

[290 rows x 10 columns]

In [40]:
# 13. Find the average price for each city.
print(df.groupby("city")["price"].mean())

city
Ahmedabad     8514.107903
Bengaluru    11333.005293
Chennai      13742.084010
Delhi        15585.384858
Goa           9955.464090
Jaipur       20463.922502
Mumbai       13173.127396
Pune          8671.754514
Name: price, dtype: float64

In [43]:
# 14. Find the top 5 most expensive listings.
top_5 = df.sort_values(by='price', ascending=False).head(5)

top_5

,listing_id,city,property_type,price,rating,reviews,minimum_nights,host,availability_days,last_booked
804,1804,Goa,House,390000.0,4.2,1600.0,4,Host_197,255,2025-12-13
484,1484,Jaipur,Villa,380000.0,3.7,77.0,7,Host_166,55,2025-01-09
713,1713,Jaipur,Villa,370000.0,4.6,28.0,11,Host_204,78,2025-03-24
932,1932,Chennai,Apartment,360000.0,4.9,161.0,14,Host_182,340,2025-09-01
954,1954,Mumbai,Loft,350000.0,4.3,126.0,4,Host_159,40,2025-01-31

In [17]:
# 15. Find listings with reviews > 200.
print(df[df["reviews"] > 200])

     listing_id       city property_type    price  rating  reviews  \
0          1000      Delhi     Apartment   5412.0     3.8    211.0
1          1001     Mumbai     Apartment   7670.0     4.3    214.0
2          1002  Ahmedabad         Villa   3813.0     4.3   1100.0
9          1009       Pune         Villa   5883.0     3.3    214.0
11         1011     Mumbai          Loft   4454.0     4.6    209.0
..          ...        ...           ...      ...     ...      ...
956        1956    Chennai        Studio   6778.0     4.2    240.0
962        1962    Chennai          Loft   2832.0     4.5    216.0
963        1963      Delhi        Studio  10028.0     4.7    212.0
966        1966       Pune          Loft   3185.0     5.0    284.0
979        1979    Chennai        Studio   3437.0     3.8    210.0

     minimum_nights      host  availability_days last_booked
0                 9   Host_23                302  2025-08-05
1                 9  Host_166                332  2025-12-26
2                 7   Host_88                142  2025-03-21
9                 8   Host_37                135  2025-03-13
11               10   Host_17                197  2025-07-15
..              ...       ...                ...         ...
956               7  Host_166                147  2025-01-13
962               8    Host_6                195  2025-08-07
963               5   Host_98                237  2025-06-06
966               2   Host_99                289  2025-03-25
979               6   Host_81                122  2025-07-04

[118 rows x 10 columns]

In [45]:
# 16. Filter Apartment listings in Mumbai.
 
mumbai_apartments = df[
    (df["city"] == "Mumbai") &
    (df["property_type"] == "Apartment")
]

print(mumbai_apartments)

     listing_id    city property_type         price  rating  reviews  \
1          1001  Mumbai     Apartment   7670.000000     4.3    214.0
43         1043  Mumbai     Apartment   5094.000000     3.7    221.0
123        1123  Mumbai     Apartment   4638.000000     4.2    156.0
194        1194  Mumbai     Apartment   3638.000000     4.2    165.0
197        1197  Mumbai     Apartment  12190.541535     3.8     48.0
231        1231  Mumbai     Apartment   5171.000000     4.6    209.0
258        1258  Mumbai     Apartment   8576.000000     3.9      5.0
330        1330  Mumbai     Apartment   5718.000000     4.1     16.0
369        1369  Mumbai     Apartment   6517.000000     4.7    108.0
404        1404  Mumbai     Apartment   4059.000000     4.3     83.0
411        1411  Mumbai     Apartment   4315.000000     5.0    133.0
445        1445  Mumbai     Apartment   1181.000000     4.5    255.0
452        1452  Mumbai     Apartment   4334.000000     3.7     46.0
455        1455  Mumbai     Apartment   5033.000000     4.0     84.0
495        1495  Mumbai     Apartment   3305.000000     4.2    136.0
576        1576  Mumbai     Apartment   4160.000000     4.5     45.0
697        1697  Mumbai     Apartment   3159.000000     4.1     37.0
869        1869  Mumbai     Apartment   4518.000000     4.4    142.0

     minimum_nights      host  availability_days last_booked
1                 9  Host_166                332  2025-12-26
43                7  Host_156                261  2025-03-01
123              10   Host_53                 35  2025-10-11
194               9  Host_230                145  2025-02-10
197              11   Host_54                292  2025-08-02
231              15  Host_230                360  2025-06-09
258               4   Host_18                362  2025-03-19
330               3  Host_166                 18  2025-10-11
369               9  Host_185                276  2025-05-16
404              13  Host_196                 45  2025-03-08
411               7  Host_114                194  2025-03-05
445              14  Host_223                226  2025-04-26
452               1  Host_166                164  2025-07-15
455              11  Host_109                 53  2025-04-16
495               2   Host_17                134  2025-04-24
576               1   Host_75                332  2025-07-17
697               7  Host_136                201  2025-09-03
869              15  Host_166                132  2025-07-12

In [46]:
# 17. Sort by price in descending order.
sorted_price = df.sort_values(by='price', ascending=False)

print(sorted_price)

     listing_id       city property_type     price  rating  reviews  \
804        1804        Goa         House  390000.0     4.2   1600.0
484        1484     Jaipur         Villa  380000.0     3.7     77.0
713        1713     Jaipur         Villa  370000.0     4.6     28.0
932        1932    Chennai     Apartment  360000.0     4.9    161.0
954        1954     Mumbai          Loft  350000.0     4.3    126.0
..          ...        ...           ...       ...     ...      ...
417        1417     Jaipur          Loft     800.0     4.6      0.0
634        1634        Goa         House     800.0     4.8     61.0
924        1924       Pune         Villa     800.0     4.7      0.0
49         1049     Jaipur         House     800.0     4.0     98.0
202        1202  Ahmedabad         House     800.0     4.8    183.0

     minimum_nights      host  availability_days last_booked
804               4  Host_197                255  2025-12-13
484               7  Host_166                 55  2025-01-09
713              11  Host_204                 78  2025-03-24
932              14  Host_182                340  2025-09-01
954               4  Host_159                 40  2025-01-31
..              ...       ...                ...         ...
417              14  Host_166                184  2025-12-13
634               3  Host_170                342  2025-02-09
924               1   Host_96                 71  2025-10-23
49               13   Host_61                344  2025-06-08
202              12   Host_81                 97  2025-03-23

[980 rows x 10 columns]

In [47]:
# 18. Create a new column 'price_per_night' (same as price).
df["price_per_night"] = df["price"]

df.head()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10800\2515849425.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["price_per_night"] = df["price"]

,listing_id,city,property_type,price,rating,reviews,minimum_nights,host,availability_days,last_booked,price_per_night
0,1000,Delhi,Apartment,5412.0,3.8,211.0,9,Host_23,302,2025-08-05,5412.0
1,1001,Mumbai,Apartment,7670.0,4.3,214.0,9,Host_166,332,2025-12-26,7670.0
2,1002,Ahmedabad,Villa,3813.0,4.3,1100.0,7,Host_88,142,2025-03-21,3813.0
3,1003,Goa,Loft,4204.0,3.9,NaN,6,Host_166,135,2025-01-23,4204.0
4,1004,Chennai,House,9020.0,5.0,93.0,15,Host_221,185,2025-10-23,9020.0

In [48]:
# 19. Detect outliers in 'price' using the IQR method.

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[(df["price"] < lower_limit) | (df["price"] > upper_limit)]

print(outliers)

     listing_id       city property_type     price  rating  reviews  \
24         1024    Chennai         House  310000.0     4.6    150.0
83         1083      Delhi         Villa  109048.0     4.2     46.0
108        1108  Bengaluru     Apartment  340000.0     4.4     72.0
110        1110  Ahmedabad        Studio  300000.0     4.3    271.0
140        1140      Delhi          Loft  280000.0     4.9    186.0
148        1148      Delhi         House  320000.0     4.1    101.0
170        1170    Chennai          Loft   78266.0     3.5    164.0
260        1260    Chennai     Apartment  119391.0     4.2    104.0
318        1318       Pune         Villa  270000.0     4.9     29.0
326        1326  Bengaluru     Apartment  115065.0     4.2    201.0
361        1361     Jaipur        Studio  330000.0     4.0      0.0
406        1406     Mumbai        Studio   50540.0     3.6     82.0
409        1409  Bengaluru          Loft   79402.0     4.2     83.0
431        1431     Mumbai        Studio  260000.0     3.6     26.0
458        1458       Pune     Apartment  144409.0     4.4     33.0
484        1484     Jaipur         Villa  380000.0     3.7     77.0
601        1601       Pune         Villa   83175.0     4.8    126.0
624        1624      Delhi        Studio  131650.0     4.5     89.0
625        1625     Jaipur         Villa  290000.0     4.4     33.0
643        1643     Jaipur         Villa  250000.0     4.3    125.0
668        1668      Delhi         House  115234.0     3.3    179.0
682        1682  Ahmedabad         Villa   73516.0     4.3    218.0
699        1699        Goa     Apartment  137691.0     3.9    222.0
713        1713     Jaipur         Villa  370000.0     4.6     28.0
781        1781    Chennai          Loft  101508.0     5.0     51.0
804        1804        Goa         House  390000.0     4.2   1600.0
827        1827     Mumbai         House  125550.0     4.1    143.0
859        1859  Bengaluru          Loft  121766.0     3.6    235.0
882        1882      Delhi          Loft  147405.0     4.4    176.0
932        1932    Chennai     Apartment  360000.0     4.9    161.0
946        1946        Goa        Studio   53662.0     4.0    183.0
954        1954     Mumbai          Loft  350000.0     4.3    126.0

     minimum_nights      host  availability_days last_booked  price_per_night
24               13  Host_218                121  2025-03-27         310000.0
83                1   Host_60                147  2025-12-28         109048.0
108               5  Host_117                154  2025-04-12         340000.0
110              12  Host_128                146  2025-04-28         300000.0
140               7  Host_125                310  2025-08-15         280000.0
148              14   Host_38                120  2025-02-22         320000.0
170              12  Host_156                270  2025-08-05          78266.0
260               5  Host_166                257  2025-12-24         119391.0
318               5  Host_200                353  2025-01-14         270000.0
326              13  Host_211                132  2025-03-27         115065.0
361              10  Host_101                290  2025-01-17         330000.0
406              12  Host_225                176  2025-06-09          50540.0
409              12    Host_6                301  2025-09-16          79402.0
431               9  Host_134                191  2025-12-26         260000.0
458              10   Host_12                358  2025-02-07         144409.0
484               7  Host_166                 55  2025-01-09         380000.0
601               8  Host_140                  2  2025-11-08          83175.0
624               9   Host_90                281  2025-06-13         131650.0
625               3   Host_19                159  2025-11-10         290000.0
643              12  Host_227                249  2025-12-03         250000.0
668              15   Host_10                340  2025-07-19         115234.0
682              10  Host_228                145  2025-08-02          73516.0
699              14  Host_147                298  2025-01-13         137691.0
713              11  Host_204                 78  2025-03-24         370000.0
781               5   Host_24                120  2025-06-02         101508.0
804               4  Host_197                255  2025-12-13         390000.0
827              15  Host_166                213  2025-08-31         125550.0
859               7  Host_124                293  2025-06-08         121766.0
882              15  Host_182                183  2025-04-09         147405.0
932              14  Host_182                340  2025-09-01         360000.0
946               4  Host_175                342  2025-02-02          53662.0
954               4  Host_159                 40  2025-01-31         350000.0

In [49]:
# 20. Remove the detected outliers from the dataset.
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Remove outliers
df = df[(df["price"] >= lower_limit) & (df["price"] <= upper_limit)]

print(df)

     listing_id       city property_type   price  rating  reviews  \
0          1000      Delhi     Apartment  5412.0     3.8    211.0
1          1001     Mumbai     Apartment  7670.0     4.3    214.0
2          1002  Ahmedabad         Villa  3813.0     4.3   1100.0
3          1003        Goa          Loft  4204.0     3.9      NaN
4          1004    Chennai         House  9020.0     5.0     93.0
..          ...        ...           ...     ...     ...      ...
975        1975      Delhi          Loft  6764.0     4.3    165.0
976        1976  Ahmedabad          Loft  3348.0     3.7    149.0
977        1977       Pune     Apartment  7083.0     3.5    134.0
978        1978     Mumbai          Loft  5656.0     4.1    137.0
979        1979    Chennai        Studio  3437.0     3.8    210.0

     minimum_nights      host  availability_days last_booked  price_per_night
0                 9   Host_23                302  2025-08-05           5412.0
1                 9  Host_166                332  2025-12-26           7670.0
2                 7   Host_88                142  2025-03-21           3813.0
3                 6  Host_166                135  2025-01-23           4204.0
4                15  Host_221                185  2025-10-23           9020.0
..              ...       ...                ...         ...              ...
975              12   Host_47                 98  2025-05-13           6764.0
976               7   Host_32                141  2025-02-02           3348.0
977               2    Host_3                 31  2025-05-17           7083.0
978               9  Host_247                136  2025-09-06           5656.0
979               6   Host_81                122  2025-07-04           3437.0

[948 rows x 11 columns]

In [21]:
# 21. Verify that no duplicates remain.
print(df.duplicated().sum())

0

In [22]:
# 22. Verify that missing values have been handled.
print(df.isnull().sum())

listing_id            0
city                  0
property_type         0
price                 0
rating                0
reviews              49
minimum_nights        0
host                  0
availability_days     0
last_booked           0
dtype: int64

In [31]:
# 23. Save the cleaned dataset as 'airbnb_cleaned.csv'.
# df_clean.to_csv("cleanedAirBnb.csv")